name: KP Law Firm (Grid)
favicon: null
layout_spectrum: 0.82213
typography_spectrum: 0.50192
title: KP Law Firm
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
