name: KP Law Firm (Grid-app share)
favicon: null
layout_spectrum: 0.24971
typography_spectrum: 1
title: KP Law Firm
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#222222'
    - '#ffffff'
    - '#616161'
    - '#a02013'
    - '#80abbb'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
